export const ACCREDITATIONS = [
  "Joint Commission International (JCI)",
  "National Accreditation Board for Hospitals (NABH)",
  "National Accreditation Board for Testing and Calibration Laboratories (NABL)",
  "ISO 9001:2015",
  "ISO 15189 Medical Laboratory Accreditation",
  "CAP Accredited Laboratory",
  "ACHSI Accreditation",
  "Temos International Healthcare Accreditation",
  "Planetree Person-Centered Care Certification",
  "DNV Healthcare Accreditation",
  "Magnet Recognition Program",
  "American College of Radiology (ACR)",
  "College of American Pathologists (CAP)",
  "European Society of Cardiology Center of Excellence",
  "WHO Good Clinical Practice (GCP)",
  "Good Manufacturing Practice (GMP)",
  "Good Distribution Practice (GDP)",
  "ISO 13485 Medical Devices",
  "Health Level Seven (HL7) Compliance",
  "HIPAA Compliance",
];