export interface MockVendorSeed {
  companyName: string;

  email: string;
  phone: string;
  website: string;

  mainCategory: string;
  subCategory: string;
  specialty: string;

  country: string;
  state: string;
  city: string;

  description: string;

  tier: "PREMIUM" | "STANDARD" | "BASIC";

  featured: boolean;

  rating: number;

  staffCount: string;

  establishedYear: number;
}

export const mockVendors: MockVendorSeed[] = [
  {
    companyName: "Meridian Medical Centre",
    email: "info@meridianmedical.com",
    phone: "+91 44 4000 1000",
    website: "https://www.meridianmedical.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Cardiology",
    country: "India",
    state: "Tamil Nadu",
    city: "Chennai",
    description:
      "A leading multi-specialty hospital delivering advanced cardiac, surgical and critical care services.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.9,
    staffCount: "1200+",
    establishedYear: 1998,
  },

  {
    companyName: "NovaCare Hospital",
    email: "info@novacarehospital.com",
    phone: "+91 80 4100 2200",
    website: "https://www.novacarehospital.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Orthopedics",
    country: "India",
    state: "Karnataka",
    city: "Bengaluru",
    description:
      "Regional referral hospital specializing in orthopedics, trauma care and rehabilitation.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "900+",
    establishedYear: 2003,
  },

  {
    companyName: "Horizon Heart Institute",
    email: "info@horizonheart.com",
    phone: "+91 22 4700 3100",
    website: "https://www.horizonheart.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Heart Institute",
    specialty: "Interventional Cardiology",
    country: "India",
    state: "Maharashtra",
    city: "Mumbai",
    description:
      "Dedicated cardiac institute offering advanced interventional and surgical heart care.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.9,
    staffCount: "950+",
    establishedYear: 2001,
  },

  {
    companyName: "Evergreen Children's Hospital",
    email: "info@evergreenchildrens.com",
    phone: "+91 11 4500 5000",
    website: "https://www.evergreenchildrens.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Children's Hospital",
    specialty: "Pediatrics",
    country: "India",
    state: "Delhi",
    city: "New Delhi",
    description:
      "Comprehensive pediatric hospital providing specialized care for infants and children.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "500+",
    establishedYear: 2008,
  },

  {
    companyName: "Apex Cancer Institute",
    email: "info@apexcancer.com",
    phone: "+91 40 4600 4200",
    website: "https://www.apexcancer.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Cancer Center",
    specialty: "Medical Oncology",
    country: "India",
    state: "Telangana",
    city: "Hyderabad",
    description:
      "Advanced oncology center delivering chemotherapy, radiation therapy and cancer surgery.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "780+",
    establishedYear: 2006,
  },

  {
    companyName: "BluePeak Medical Center",
    email: "info@bluepeakmedical.com",
    phone: "+971 4 510 2200",
    website: "https://www.bluepeakmedical.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Medical Center",
    specialty: "Internal Medicine",
    country: "UAE",
    state: "Dubai",
    city: "Dubai",
    description:
      "Modern multidisciplinary medical center serving local and international patients.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "420+",
    establishedYear: 2010,
  },

  {
    companyName: "Royal Crescent Hospital",
    email: "info@royalcrescenthospital.com",
    phone: "+971 2 610 1100",
    website: "https://www.royalcrescenthospital.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Neurology",
    country: "UAE",
    state: "Abu Dhabi",
    city: "Abu Dhabi",
    description:
      "Regional neurological and multi-specialty hospital with comprehensive inpatient care.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "980+",
    establishedYear: 2005,
  },

  {
    companyName: "Pacific Wellness Hospital",
    email: "info@pacificwellness.com",
    phone: "+65 6300 4200",
    website: "https://www.pacificwellness.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Gastroenterology",
    country: "Singapore",
    state: "Singapore",
    city: "Singapore",
    description:
      "Comprehensive hospital offering gastroenterology, surgery and preventive healthcare.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "760+",
    establishedYear: 2009,
  },

  {
    companyName: "Anatolia Medical Centre",
    email: "info@anatoliamedical.com",
    phone: "+90 212 450 2200",
    website: "https://www.anatoliamedical.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Neurosurgery",
    country: "Turkey",
    state: "Istanbul",
    city: "Istanbul",
    description:
      "International healthcare provider specializing in neurological and complex surgical procedures.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "1100+",
    establishedYear: 1999,
  },

  {
    companyName: "Harmony General Hospital",
    email: "info@harmonygeneral.com",
    phone: "+66 2 450 3000",
    website: "https://www.harmonygeneral.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "General Surgery",
    country: "Thailand",
    state: "Bangkok",
    city: "Bangkok",
    description:
      "General hospital providing surgical, emergency and inpatient medical services.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "640+",
    establishedYear: 2007,
  },

  {
    companyName: "Silver Oak Medical Centre",
    email: "info@silveroakmedical.com",
    phone: "+91 79 4300 2100",
    website: "https://www.silveroakmedical.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Medical Center",
    specialty: "Endocrinology",
    country: "India",
    state: "Gujarat",
    city: "Ahmedabad",
    description:
      "Comprehensive medical centre delivering specialist consultations and preventive healthcare.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "380+",
    establishedYear: 2011,
  },

  {
    companyName: "Grand Oak Hospital",
    email: "info@grandoakhospital.com",
    phone: "+91 20 4700 8100",
    website: "https://www.grandoakhospital.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Pulmonology",
    country: "India",
    state: "Maharashtra",
    city: "Pune",
    description:
      "Modern multi-specialty hospital with advanced respiratory and critical care services.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "860+",
    establishedYear: 2004,
  },

  {
    companyName: "RiverStone Medical Institute",
    email: "info@riverstonemedical.com",
    phone: "+91 33 4800 2600",
    website: "https://www.riverstonemedical.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Nephrology",
    country: "India",
    state: "West Bengal",
    city: "Kolkata",
    description:
      "Specialized hospital providing advanced nephrology, dialysis and transplant support.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "640+",
    establishedYear: 2007,
  },

  {
    companyName: "Unity Women's Health Centre",
    email: "info@unitywomenshealth.com",
    phone: "+91 80 4600 3500",
    website: "https://www.unitywomenshealth.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Women's Health & Maternity Center",
    specialty: "Gynecology",
    country: "India",
    state: "Karnataka",
    city: "Bengaluru",
    description:
      "Dedicated women's healthcare centre providing maternity, fertility and gynecological services.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "410+",
    establishedYear: 2010,
  },

  {
    companyName: "Summit Eye Institute",
    email: "info@summiteye.com",
    phone: "+971 4 530 1200",
    website: "https://www.summiteye.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Eye Hospital / Ophthalmology Center",
    specialty: "LASIK",
    country: "UAE",
    state: "Dubai",
    city: "Dubai",
    description:
      "Advanced ophthalmology centre specializing in laser vision correction and retinal care.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.9,
    staffCount: "260+",
    establishedYear: 2013,
  },

  {
    companyName: "Golden Palm Hospital",
    email: "info@goldenpalmhospital.com",
    phone: "+971 2 620 3400",
    website: "https://www.goldenpalmhospital.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Critical Care",
    country: "UAE",
    state: "Abu Dhabi",
    city: "Abu Dhabi",
    description:
      "Comprehensive tertiary care hospital with advanced emergency and intensive care facilities.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "980+",
    establishedYear: 2002,
  },

  {
    companyName: "Harbour Medical Centre",
    email: "info@harbourmedical.com",
    phone: "+65 6400 2200",
    website: "https://www.harbourmedical.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Medical Center",
    specialty: "Internal Medicine",
    country: "Singapore",
    state: "Singapore",
    city: "Singapore",
    description:
      "Patient-focused medical centre providing specialist outpatient care and executive health services.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "330+",
    establishedYear: 2012,
  },

  {
    companyName: "Ankara Regional Hospital",
    email: "info@ankararegional.com",
    phone: "+90 312 420 1800",
    website: "https://www.ankararegional.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Emergency Medicine",
    country: "Turkey",
    state: "Ankara",
    city: "Ankara",
    description:
      "Large regional hospital delivering emergency medicine and comprehensive inpatient care.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "720+",
    establishedYear: 2008,
  },

  {
    companyName: "Lotus Specialty Hospital",
    email: "info@lotusspecialty.com",
    phone: "+66 2 490 6600",
    website: "https://www.lotusspecialty.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Specialty Clinic",
    specialty: "Dermatology",
    country: "Thailand",
    state: "Bangkok",
    city: "Bangkok",
    description:
      "Specialty healthcare centre offering dermatology, aesthetic medicine and outpatient procedures.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "180+",
    establishedYear: 2016,
  },

  {
    companyName: "Emerald Care Hospital",
    email: "info@emeraldcarehospital.com",
    phone: "+60 3 5200 4800",
    website: "https://www.emeraldcarehospital.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Gastroenterology",
    country: "Malaysia",
    state: "Selangor",
    city: "Petaling Jaya",
    description:
      "Multi-specialty hospital delivering gastrointestinal, surgical and preventive healthcare services.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "610+",
    establishedYear: 2009,
  },

    {
    companyName: "Pinnacle Medical Hospital",
    email: "info@pinnaclemedicalhospital.com",
    phone: "+91 47 4200 5100",
    website: "https://www.pinnaclemedicalhospital.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Neurology",
    country: "India",
    state: "Kerala",
    city: "Kochi",
    description: "Comprehensive tertiary care hospital providing neurological, cardiac and surgical services.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "980+",
    establishedYear: 2002,
  },

  {
    companyName: "WestBridge Medical Centre",
    email: "info@westbridgemedical.com",
    phone: "+91 73 4300 1400",
    website: "https://www.westbridgemedical.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Medical Center",
    specialty: "Internal Medicine",
    country: "India",
    state: "Madhya Pradesh",
    city: "Bhopal",
    description: "Patient-centered medical centre offering multidisciplinary outpatient and inpatient care.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "340+",
    establishedYear: 2012,
  },

  {
    companyName: "Unity Orthopedic Center",
    email: "info@unityortho.com",
    phone: "+91 17 4300 6700",
    website: "https://www.unityortho.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Orthopedic Center",
    specialty: "Joint Replacement",
    country: "India",
    state: "Punjab",
    city: "Ludhiana",
    description: "Specialized orthopedic centre providing joint replacement, trauma and sports injury care.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "290+",
    establishedYear: 2011,
  },

  {
    companyName: "Cedar Women's Hospital",
    email: "info@cedarwomenshospital.com",
    phone: "+91 14 4200 8500",
    website: "https://www.cedarwomenshospital.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Women's Health & Maternity Center",
    specialty: "Obstetrics",
    country: "India",
    state: "Rajasthan",
    city: "Jaipur",
    description: "Dedicated women's hospital providing maternity, obstetrics and fertility services.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "360+",
    establishedYear: 2014,
  },

  {
    companyName: "Vision Plus Eye Hospital",
    email: "info@visionpluseye.com",
    phone: "+971 6 530 4400",
    website: "https://www.visionpluseye.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Eye Hospital / Ophthalmology Center",
    specialty: "Retina",
    country: "UAE",
    state: "Sharjah",
    city: "Sharjah",
    description: "Advanced eye hospital providing retinal surgery, cataract care and LASIK treatments.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.9,
    staffCount: "210+",
    establishedYear: 2015,
  },

  {
    companyName: "Alpine General Hospital",
    email: "info@alpinegeneral.com",
    phone: "+968 24 520 3300",
    website: "https://www.alpinegeneral.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Pulmonology",
    country: "Oman",
    state: "Muscat",
    city: "Muscat",
    description: "Modern multi-specialty hospital serving respiratory, internal medicine and surgical patients.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "540+",
    establishedYear: 2010,
  },

  {
    companyName: "Prime Children's Medical Centre",
    email: "info@primechildrens.com",
    phone: "+966 11 430 2800",
    website: "https://www.primechildrens.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Children's Hospital",
    specialty: "Pediatric Cardiology",
    country: "Saudi Arabia",
    state: "Riyadh",
    city: "Riyadh",
    description: "Dedicated pediatric hospital specializing in congenital heart disease and neonatal care.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "430+",
    establishedYear: 2008,
  },

  {
    companyName: "Sunrise Medical Institute",
    email: "info@sunrisemedicalinstitute.com",
    phone: "+230 210 5400",
    website: "https://www.sunrisemedicalinstitute.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Nephrology",
    country: "Mauritius",
    state: "Port Louis",
    city: "Port Louis",
    description: "Regional hospital providing renal care, dialysis and multidisciplinary medical services.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "390+",
    establishedYear: 2011,
  },

  {
    companyName: "Victoria Care Hospital",
    email: "info@victoriacarehospital.com",
    phone: "+254 20 520 2100",
    website: "https://www.victoriacarehospital.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Emergency Medicine",
    country: "Kenya",
    state: "Nairobi County",
    city: "Nairobi",
    description: "Comprehensive emergency and trauma hospital serving local and international patients.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "620+",
    establishedYear: 2007,
  },

  {
    companyName: "Trinity Specialty Hospital",
    email: "info@trinityspecialty.com",
    phone: "+91 67 4300 7800",
    website: "https://www.trinityspecialty.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Specialty Clinic",
    specialty: "Plastic Surgery",
    country: "India",
    state: "Odisha",
    city: "Bhubaneswar",
    description: "Specialty surgical centre offering reconstructive and cosmetic surgical procedures.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "170+",
    establishedYear: 2017,
  },

    {
    companyName: "NorthStar Medical Hospital",
    email: "info@northstarmedical.com",
    phone: "+91 48 4300 2500",
    website: "https://www.northstarmedical.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Urology",
    country: "India",
    state: "Kerala",
    city: "Thiruvananthapuram",
    description: "Comprehensive tertiary care hospital providing advanced urology, laparoscopic and critical care services.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "890+",
    establishedYear: 2005,
  },

  {
    companyName: "Lakeside Medical Centre",
    email: "info@lakesidemedical.com",
    phone: "+91 61 4200 4100",
    website: "https://www.lakesidemedical.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Medical Center",
    specialty: "Internal Medicine",
    country: "India",
    state: "Bihar",
    city: "Patna",
    description: "Regional medical centre delivering multidisciplinary consultations and preventive healthcare.",
    tier: "STANDARD",
    featured: false,
    rating: 4.5,
    staffCount: "320+",
    establishedYear: 2014,
  },

  {
    companyName: "Redwood Heart Hospital",
    email: "info@redwoodheart.com",
    phone: "+91 79 4600 5100",
    website: "https://www.redwoodheart.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Heart Institute",
    specialty: "Cardiac Surgery",
    country: "India",
    state: "Gujarat",
    city: "Ahmedabad",
    description: "Dedicated cardiac hospital providing minimally invasive and complex heart surgery.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.9,
    staffCount: "760+",
    establishedYear: 2004,
  },

  {
    companyName: "Prime Oncology Centre",
    email: "info@primeoncology.com",
    phone: "+91 44 4800 7800",
    website: "https://www.primeoncology.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Cancer Center",
    specialty: "Radiation Oncology",
    country: "India",
    state: "Tamil Nadu",
    city: "Chennai",
    description: "Comprehensive cancer centre offering precision radiotherapy, chemotherapy and surgical oncology.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "640+",
    establishedYear: 2009,
  },

  {
    companyName: "Crystal Vision Eye Centre",
    email: "info@crystalvisioneye.com",
    phone: "+971 4 570 3400",
    website: "https://www.crystalvisioneye.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Eye Hospital / Ophthalmology Center",
    specialty: "Cataract",
    country: "UAE",
    state: "Dubai",
    city: "Dubai",
    description: "Advanced ophthalmology centre providing cataract, cornea and refractive surgery.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "180+",
    establishedYear: 2016,
  },

  {
    companyName: "Crescent Women's Hospital",
    email: "info@crescentwomenshospital.com",
    phone: "+971 2 640 2700",
    website: "https://www.crescentwomenshospital.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Women's Health & Maternity Center",
    specialty: "Obstetrics",
    country: "UAE",
    state: "Abu Dhabi",
    city: "Abu Dhabi",
    description: "Women's specialty hospital providing maternity, neonatal and gynecological services.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "370+",
    establishedYear: 2012,
  },

  {
    companyName: "Harbour Children's Hospital",
    email: "info@harbourchildrens.com",
    phone: "+65 6400 8100",
    website: "https://www.harbourchildrens.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Children's Hospital",
    specialty: "Pediatric Neurology",
    country: "Singapore",
    state: "Singapore",
    city: "Singapore",
    description: "Dedicated children's hospital providing advanced pediatric neurological and neonatal care.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.9,
    staffCount: "460+",
    establishedYear: 2011,
  },

  {
    companyName: "Bosphorus General Hospital",
    email: "info@bosphorusgeneral.com",
    phone: "+90 216 450 5200",
    website: "https://www.bosphorusgeneral.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "General Surgery",
    country: "Turkey",
    state: "Istanbul",
    city: "Istanbul",
    description: "Large multidisciplinary hospital providing surgical excellence and emergency medical care.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "940+",
    establishedYear: 2003,
  },

  {
    companyName: "Royal Lotus Medical Centre",
    email: "info@royallotusmedical.com",
    phone: "+66 2 560 1800",
    website: "https://www.royallotusmedical.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Medical Center",
    specialty: "Gastroenterology",
    country: "Thailand",
    state: "Bangkok",
    city: "Bangkok",
    description: "International medical centre delivering specialist gastroenterology and digestive care.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "350+",
    establishedYear: 2013,
  },

  {
    companyName: "Emerald Regional Hospital",
    email: "info@emeraldregional.com",
    phone: "+60 3 5400 7600",
    website: "https://www.emeraldregional.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Critical Care",
    country: "Malaysia",
    state: "Kuala Lumpur",
    city: "Kuala Lumpur",
    description: "Regional referral hospital providing intensive care, trauma services and specialist surgery.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "710+",
    establishedYear: 2008,
  },

    {
    companyName: "Oakridge Medical Hospital",
    email: "info@oakridgemedical.com",
    phone: "+91 52 4300 8200",
    website: "https://www.oakridgemedical.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Nephrology",
    country: "India",
    state: "Uttar Pradesh",
    city: "Lucknow",
    description: "Advanced tertiary care hospital offering nephrology, internal medicine and surgical specialties.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "840+",
    establishedYear: 2006,
  },

  {
    companyName: "Central Valley Hospital",
    email: "info@centralvalleyhospital.com",
    phone: "+91 75 4300 9200",
    website: "https://www.centralvalleyhospital.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Emergency Medicine",
    country: "India",
    state: "Madhya Pradesh",
    city: "Indore",
    description: "Regional referral hospital providing emergency, trauma and intensive care services.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "620+",
    establishedYear: 2010,
  },

  {
    companyName: "Blue Horizon Heart Centre",
    email: "info@bluehorizonheart.com",
    phone: "+971 4 590 2800",
    website: "https://www.bluehorizonheart.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Heart Institute",
    specialty: "Cardiac Electrophysiology",
    country: "UAE",
    state: "Dubai",
    city: "Dubai",
    description: "Dedicated cardiac centre specializing in electrophysiology and minimally invasive cardiac procedures.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.9,
    staffCount: "520+",
    establishedYear: 2014,
  },

  {
    companyName: "Sunrise Oncology Hospital",
    email: "info@sunriseoncology.com",
    phone: "+65 6500 4100",
    website: "https://www.sunriseoncology.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Cancer Center",
    specialty: "Surgical Oncology",
    country: "Singapore",
    state: "Singapore",
    city: "Singapore",
    description: "Comprehensive oncology hospital delivering multidisciplinary cancer treatment and supportive care.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.9,
    staffCount: "540+",
    establishedYear: 2012,
  },

  {
    companyName: "Anatolia Women's Hospital",
    email: "info@anatoliawomen.com",
    phone: "+90 232 480 3300",
    website: "https://www.anatoliawomen.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Women's Health & Maternity Center",
    specialty: "Maternal Medicine",
    country: "Turkey",
    state: "Izmir",
    city: "Izmir",
    description: "Women's specialty hospital providing advanced maternity, fertility and maternal medicine services.",
    tier: "STANDARD",
    featured: false,
    rating: 4.8,
    staffCount: "340+",
    establishedYear: 2015,
  },

  {
    companyName: "Golden Coast Medical Centre",
    email: "info@goldencoastmedical.com",
    phone: "+66 76 450 1200",
    website: "https://www.goldencoastmedical.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Medical Center",
    specialty: "Family Medicine",
    country: "Thailand",
    state: "Phuket",
    city: "Phuket",
    description: "Modern medical centre serving residents and international visitors with comprehensive family healthcare.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "260+",
    establishedYear: 2017,
  },

  {
    companyName: "Summit General Hospital",
    email: "info@summitgeneral.com",
    phone: "+60 7 560 2200",
    website: "https://www.summitgeneral.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Internal Medicine",
    country: "Malaysia",
    state: "Johor",
    city: "Johor Bahru",
    description: "Regional multi-specialty hospital providing medical, surgical and emergency care.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "690+",
    establishedYear: 2009,
  },

  {
    companyName: "Prime Coast Hospital",
    email: "info@primecoasthospital.com",
    phone: "+254 41 520 4600",
    website: "https://www.primecoasthospital.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "Critical Care",
    country: "Kenya",
    state: "Mombasa County",
    city: "Mombasa",
    description: "Regional hospital delivering emergency, trauma and intensive care medicine.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "510+",
    establishedYear: 2011,
  },

  {
    companyName: "Island Medical Hospital",
    email: "info@islandmedicalhospital.com",
    phone: "+230 460 3200",
    website: "https://www.islandmedicalhospital.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Hospital",
    specialty: "General Surgery",
    country: "Mauritius",
    state: "Plaines Wilhems",
    city: "Curepipe",
    description: "Modern hospital providing general surgery, emergency medicine and specialist consultations.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "430+",
    establishedYear: 2013,
  },

  {
    companyName: "Desert Bloom Medical Centre",
    email: "info@desertbloommedical.com",
    phone: "+968 24 560 1800",
    website: "https://www.desertbloommedical.com",
    mainCategory: "Hospitals & Medical Providers",
    subCategory: "Medical Center",
    specialty: "Endocrinology",
    country: "Oman",
    state: "Muscat",
    city: "Muscat",
    description: "Specialist medical centre providing diabetes, endocrine and preventive healthcare services.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "240+",
    establishedYear: 2018,
  },

    {
    companyName: "Precision Diagnostics",
    email: "info@precisiondiagnostics.com",
    phone: "+91 44 5100 1200",
    website: "https://www.precisiondiagnostics.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Diagnostic Laboratory",
    specialty: "Clinical Pathology",
    country: "India",
    state: "Tamil Nadu",
    city: "Chennai",
    description: "Full-service diagnostic laboratory providing pathology, microbiology and preventive health screening.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "220+",
    establishedYear: 2008,
  },

  {
    companyName: "PrimeLab Diagnostics",
    email: "info@primelabdiagnostics.com",
    phone: "+91 80 5200 3300",
    website: "https://www.primelabdiagnostics.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Diagnostic Laboratory",
    specialty: "Clinical Biochemistry",
    country: "India",
    state: "Karnataka",
    city: "Bengaluru",
    description: "Advanced diagnostic laboratory specializing in preventive health checkups and laboratory medicine.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "170+",
    establishedYear: 2012,
  },

  {
    companyName: "Advanced Imaging Centre",
    email: "info@advancedimagingcentre.com",
    phone: "+91 22 5300 4200",
    website: "https://www.advancedimagingcentre.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Medical Imaging Center",
    specialty: "MRI & CT Imaging",
    country: "India",
    state: "Maharashtra",
    city: "Mumbai",
    description: "Comprehensive diagnostic imaging centre offering MRI, CT, Ultrasound and Digital X-Ray services.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.9,
    staffCount: "150+",
    establishedYear: 2010,
  },

  {
    companyName: "ClearView Radiology",
    email: "info@clearviewradiology.com",
    phone: "+91 40 5400 5500",
    website: "https://www.clearviewradiology.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Medical Imaging Center",
    specialty: "Radiology",
    country: "India",
    state: "Telangana",
    city: "Hyderabad",
    description: "Specialized imaging facility delivering fast and accurate radiology and diagnostic reporting.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "110+",
    establishedYear: 2014,
  },

  {
    companyName: "LifeGene Diagnostics",
    email: "info@lifegenediagnostics.com",
    phone: "+971 4 610 2400",
    website: "https://www.lifegenediagnostics.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Genetic Testing Laboratory",
    specialty: "Genetic Screening",
    country: "UAE",
    state: "Dubai",
    city: "Dubai",
    description: "Advanced genetics laboratory providing molecular diagnostics and hereditary disease screening.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "140+",
    establishedYear: 2016,
  },

  {
    companyName: "RapidCare Labs",
    email: "info@rapidcarelabs.com",
    phone: "+971 2 620 1700",
    website: "https://www.rapidcarelabs.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Diagnostic Laboratory",
    specialty: "Clinical Microbiology",
    country: "UAE",
    state: "Abu Dhabi",
    city: "Abu Dhabi",
    description: "Modern clinical laboratory delivering fast and reliable pathology and microbiology services.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "130+",
    establishedYear: 2015,
  },

  {
    companyName: "Pacific Diagnostic Centre",
    email: "info@pacificdiagnostic.com",
    phone: "+65 6600 4300",
    website: "https://www.pacificdiagnostic.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Diagnostic Laboratory",
    specialty: "Preventive Health Screening",
    country: "Singapore",
    state: "Singapore",
    city: "Singapore",
    description: "Diagnostic centre offering preventive health packages and comprehensive laboratory testing.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "180+",
    establishedYear: 2011,
  },

  {
    companyName: "Bosphorus Imaging Institute",
    email: "info@bosphorusimaging.com",
    phone: "+90 212 560 1800",
    website: "https://www.bosphorusimaging.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Medical Imaging Center",
    specialty: "PET-CT Imaging",
    country: "Turkey",
    state: "Istanbul",
    city: "Istanbul",
    description: "Advanced imaging institute specializing in PET-CT, MRI and oncology diagnostics.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.9,
    staffCount: "190+",
    establishedYear: 2009,
  },

  {
    companyName: "Lotus Diagnostic Centre",
    email: "info@lotusdiagnostic.com",
    phone: "+66 2 570 3200",
    website: "https://www.lotusdiagnostic.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Diagnostic Laboratory",
    specialty: "Clinical Pathology",
    country: "Thailand",
    state: "Bangkok",
    city: "Bangkok",
    description: "Accredited pathology laboratory providing comprehensive diagnostic and preventive testing services.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "120+",
    establishedYear: 2013,
  },

  {
    companyName: "Summit Medical Imaging",
    email: "info@summitmedicalimaging.com",
    phone: "+60 3 5700 4100",
    website: "https://www.summitmedicalimaging.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Medical Imaging Center",
    specialty: "Ultrasound & CT",
    country: "Malaysia",
    state: "Kuala Lumpur",
    city: "Kuala Lumpur",
    description: "Diagnostic imaging centre delivering high-quality ultrasound, CT and MRI examinations.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "135+",
    establishedYear: 2012,
  },

    {
    companyName: "Elite Pathology Network",
    email: "info@elitepathology.com",
    phone: "+91 33 5800 1200",
    website: "https://www.elitepathology.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Diagnostic Laboratory",
    specialty: "Clinical Pathology",
    country: "India",
    state: "West Bengal",
    city: "Kolkata",
    description: "Comprehensive pathology laboratory delivering accurate diagnostic and preventive healthcare testing.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "145+",
    establishedYear: 2011,
  },

  {
    companyName: "AccuScan Imaging Centre",
    email: "info@accuscanimaging.com",
    phone: "+91 79 5700 3100",
    website: "https://www.accuscanimaging.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Medical Imaging Center",
    specialty: "MRI & CT Imaging",
    country: "India",
    state: "Gujarat",
    city: "Ahmedabad",
    description: "Modern imaging centre providing MRI, CT Scan, Ultrasound and Digital X-Ray services.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "125+",
    establishedYear: 2014,
  },

  {
    companyName: "Vital Diagnostics Institute",
    email: "info@vitaldiagnostics.com",
    phone: "+91 48 5900 1800",
    website: "https://www.vitaldiagnostics.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Diagnostic Laboratory",
    specialty: "Clinical Microbiology",
    country: "India",
    state: "Kerala",
    city: "Kochi",
    description: "Accredited laboratory specializing in microbiology, pathology and preventive health diagnostics.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "135+",
    establishedYear: 2013,
  },

  {
    companyName: "Infinity Molecular Labs",
    email: "info@infinitymolecular.com",
    phone: "+971 4 630 4100",
    website: "https://www.infinitymolecular.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Genetic Testing Laboratory",
    specialty: "Molecular Diagnostics",
    country: "UAE",
    state: "Dubai",
    city: "Dubai",
    description: "Specialized molecular diagnostics laboratory supporting precision medicine and genetic testing.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.9,
    staffCount: "155+",
    establishedYear: 2017,
  },

  {
    companyName: "MedVision Imaging",
    email: "info@medvisionimaging.com",
    phone: "+65 6700 4200",
    website: "https://www.medvisionimaging.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Medical Imaging Center",
    specialty: "Radiology",
    country: "Singapore",
    state: "Singapore",
    city: "Singapore",
    description: "Advanced imaging centre delivering high-quality radiology and diagnostic reporting.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "165+",
    establishedYear: 2010,
  },

  {
    companyName: "Golden Crescent Diagnostics",
    email: "info@goldencrescentdiagnostics.com",
    phone: "+90 312 580 2600",
    website: "https://www.goldencrescentdiagnostics.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Diagnostic Laboratory",
    specialty: "Clinical Biochemistry",
    country: "Turkey",
    state: "Ankara",
    city: "Ankara",
    description: "Regional laboratory delivering biochemistry, pathology and wellness screening services.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "118+",
    establishedYear: 2012,
  },

  {
    companyName: "Bangkok Precision Imaging",
    email: "info@bangkokprecision.com",
    phone: "+66 2 580 4100",
    website: "https://www.bangkokprecision.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Medical Imaging Center",
    specialty: "PET-CT Imaging",
    country: "Thailand",
    state: "Bangkok",
    city: "Bangkok",
    description: "State-of-the-art imaging centre supporting oncology, neurology and cardiac diagnostics.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.9,
    staffCount: "205+",
    establishedYear: 2011,
  },

  {
    companyName: "Metro Diagnostic Labs",
    email: "info@metrodiagnosticlabs.com",
    phone: "+60 3 5800 2900",
    website: "https://www.metrodiagnosticlabs.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Diagnostic Laboratory",
    specialty: "Preventive Health Screening",
    country: "Malaysia",
    state: "Selangor",
    city: "Petaling Jaya",
    description: "Comprehensive diagnostic laboratory focused on executive health screening and pathology services.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "126+",
    establishedYear: 2015,
  },

  {
    companyName: "Coastal Diagnostic Centre",
    email: "info@coastaldiagnostic.com",
    phone: "+254 20 580 3600",
    website: "https://www.coastaldiagnostic.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Diagnostic Laboratory",
    specialty: "Clinical Pathology",
    country: "Kenya",
    state: "Nairobi County",
    city: "Nairobi",
    description: "Modern pathology laboratory providing accurate diagnostics and wellness testing.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "108+",
    establishedYear: 2016,
  },

  {
    companyName: "Island Medical Imaging",
    email: "info@islandmedicalimaging.com",
    phone: "+230 460 5200",
    website: "https://www.islandmedicalimaging.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Medical Imaging Center",
    specialty: "MRI & Ultrasound",
    country: "Mauritius",
    state: "Port Louis",
    city: "Port Louis",
    description: "Specialist imaging facility offering MRI, ultrasound and CT examinations with rapid reporting.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "95+",
    establishedYear: 2018,
  },

    {
    companyName: "NorthPoint Diagnostic Centre",
    email: "info@northpointdiagnostics.com",
    phone: "+968 24 610 1200",
    website: "https://www.northpointdiagnostics.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Diagnostic Laboratory",
    specialty: "Clinical Pathology",
    country: "Oman",
    state: "Muscat",
    city: "Muscat",
    description: "Accredited diagnostic laboratory providing pathology, microbiology and preventive health screening.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "112+",
    establishedYear: 2015,
  },

  {
    companyName: "Royal Scan Imaging",
    email: "info@royalscanimaging.com",
    phone: "+966 11 580 4100",
    website: "https://www.royalscanimaging.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Medical Imaging Center",
    specialty: "MRI & CT Imaging",
    country: "Saudi Arabia",
    state: "Riyadh",
    city: "Riyadh",
    description: "Advanced diagnostic imaging centre delivering MRI, CT and radiology services.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "170+",
    establishedYear: 2013,
  },

  {
    companyName: "LifeTrack Diagnostics",
    email: "info@lifetrackdiagnostics.com",
    phone: "+91 17 5900 2200",
    website: "https://www.lifetrackdiagnostics.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Diagnostic Laboratory",
    specialty: "Clinical Biochemistry",
    country: "India",
    state: "Punjab",
    city: "Ludhiana",
    description: "Modern diagnostic laboratory offering preventive screening and advanced pathology testing.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "118+",
    establishedYear: 2014,
  },

  {
    companyName: "Insight Molecular Diagnostics",
    email: "info@insightmolecular.com",
    phone: "+971 6 620 3600",
    website: "https://www.insightmolecular.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Genetic Testing Laboratory",
    specialty: "DNA & Genetic Analysis",
    country: "UAE",
    state: "Sharjah",
    city: "Sharjah",
    description: "Genetic diagnostics laboratory supporting precision medicine and hereditary disease screening.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.9,
    staffCount: "145+",
    establishedYear: 2018,
  },

  {
    companyName: "ClearPath Medical Imaging",
    email: "info@clearpathimaging.com",
    phone: "+65 6800 3100",
    website: "https://www.clearpathimaging.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Medical Imaging Center",
    specialty: "Digital Radiology",
    country: "Singapore",
    state: "Singapore",
    city: "Singapore",
    description: "Digital imaging centre delivering radiology, CT and MRI reporting with rapid turnaround.",
    tier: "STANDARD",
    featured: false,
    rating: 4.8,
    staffCount: "122+",
    establishedYear: 2016,
  },

  {
    companyName: "Anatolia Diagnostic Institute",
    email: "info@anatoliadiagnostics.com",
    phone: "+90 232 590 2200",
    website: "https://www.anatoliadiagnostics.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Diagnostic Laboratory",
    specialty: "Clinical Microbiology",
    country: "Turkey",
    state: "Izmir",
    city: "Izmir",
    description: "Regional diagnostic laboratory delivering microbiology and infectious disease testing.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "116+",
    establishedYear: 2015,
  },

  {
    companyName: "Thai Precision Labs",
    email: "info@thaiprecisionlabs.com",
    phone: "+66 53 570 1800",
    website: "https://www.thaiprecisionlabs.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Diagnostic Laboratory",
    specialty: "Preventive Health Screening",
    country: "Thailand",
    state: "Chiang Mai",
    city: "Chiang Mai",
    description: "Preventive diagnostics laboratory offering executive health screening and pathology services.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "104+",
    establishedYear: 2017,
  },

  {
    companyName: "Metro Imaging Specialists",
    email: "info@metroimagingspecialists.com",
    phone: "+60 7 590 4400",
    website: "https://www.metroimagingspecialists.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Medical Imaging Center",
    specialty: "Cardiac Imaging",
    country: "Malaysia",
    state: "Johor",
    city: "Johor Bahru",
    description: "Specialized imaging centre focused on cardiac MRI, CT angiography and diagnostic reporting.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "132+",
    establishedYear: 2014,
  },

  {
    companyName: "Victoria Diagnostic Network",
    email: "info@victoriadiagnostic.com",
    phone: "+254 41 590 5200",
    website: "https://www.victoriadiagnostic.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Diagnostic Laboratory",
    specialty: "Clinical Pathology",
    country: "Kenya",
    state: "Mombasa County",
    city: "Mombasa",
    description: "Accredited pathology laboratory serving hospitals, clinics and preventive healthcare programmes.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "98+",
    establishedYear: 2018,
  },

  {
    companyName: "Island Precision Imaging",
    email: "info@islandprecisionimaging.com",
    phone: "+230 430 2600",
    website: "https://www.islandprecisionimaging.com",
    mainCategory: "Diagnostics & Laboratories",
    subCategory: "Medical Imaging Center",
    specialty: "MRI & PET Imaging",
    country: "Mauritius",
    state: "Plaines Wilhems",
    city: "Curepipe",
    description: "Advanced imaging facility delivering MRI, PET imaging and specialist radiology services.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "101+",
    establishedYear: 2019,
  },

    {
    companyName: "ComfortCare Home Health",
    email: "info@comfortcarehomehealth.com",
    phone: "+91 80 6100 2200",
    website: "https://www.comfortcarehomehealth.com",
    mainCategory: "Home Healthcare & Senior Care",
    subCategory: "Home Healthcare",
    specialty: "Nursing Care",
    country: "India",
    state: "Karnataka",
    city: "Bengaluru",
    description: "Professional home healthcare services including nursing, physiotherapy and post-operative recovery support.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "210+",
    establishedYear: 2016,
  },

  {
    companyName: "EverCare Home Medical",
    email: "info@evercarehome.com",
    phone: "+91 22 6200 1800",
    website: "https://www.evercarehome.com",
    mainCategory: "Home Healthcare & Senior Care",
    subCategory: "Home Healthcare",
    specialty: "Elderly Care",
    country: "India",
    state: "Maharashtra",
    city: "Mumbai",
    description: "Comprehensive home healthcare provider delivering elderly care, nursing and rehabilitation support.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "320+",
    establishedYear: 2013,
  },

  {
    companyName: "Golden Years Senior Living",
    email: "info@goldenyearssenior.com",
    phone: "+971 4 640 1200",
    website: "https://www.goldenyearssenior.com",
    mainCategory: "Home Healthcare & Senior Care",
    subCategory: "Senior Living & Assisted Care",
    specialty: "Assisted Living",
    country: "UAE",
    state: "Dubai",
    city: "Dubai",
    description: "Premium assisted living community providing long-term care, wellness and rehabilitation services.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.9,
    staffCount: "280+",
    establishedYear: 2014,
  },

  {
    companyName: "Harmony Home Nursing",
    email: "info@harmonyhomenursing.com",
    phone: "+65 6900 1400",
    website: "https://www.harmonyhomenursing.com",
    mainCategory: "Home Healthcare & Senior Care",
    subCategory: "Home Healthcare",
    specialty: "Home Nursing",
    country: "Singapore",
    state: "Singapore",
    city: "Singapore",
    description: "Experienced home nursing provider supporting patients recovering at home after hospitalization.",
    tier: "STANDARD",
    featured: false,
    rating: 4.8,
    staffCount: "170+",
    establishedYear: 2015,
  },

  {
    companyName: "VitalHome Care",
    email: "info@vitalhomecare.com",
    phone: "+90 212 610 4200",
    website: "https://www.vitalhomecare.com",
    mainCategory: "Home Healthcare & Senior Care",
    subCategory: "Home Healthcare",
    specialty: "Physiotherapy",
    country: "Turkey",
    state: "Istanbul",
    city: "Istanbul",
    description: "Home healthcare provider delivering physiotherapy, nursing and chronic disease management.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "165+",
    establishedYear: 2017,
  },

  {
    companyName: "LifeBridge Senior Care",
    email: "info@lifebridgesenior.com",
    phone: "+66 2 610 2600",
    website: "https://www.lifebridgesenior.com",
    mainCategory: "Home Healthcare & Senior Care",
    subCategory: "Senior Living & Assisted Care",
    specialty: "Memory Care",
    country: "Thailand",
    state: "Bangkok",
    city: "Bangkok",
    description: "Senior living community specializing in dementia, memory care and assisted living.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "210+",
    establishedYear: 2016,
  },

  {
    companyName: "Prime Home Support",
    email: "info@primehomesupport.com",
    phone: "+60 3 6100 3300",
    website: "https://www.primehomesupport.com",
    mainCategory: "Home Healthcare & Senior Care",
    subCategory: "Home Healthcare",
    specialty: "Palliative Care",
    country: "Malaysia",
    state: "Kuala Lumpur",
    city: "Kuala Lumpur",
    description: "Compassionate home healthcare provider offering palliative, nursing and family support services.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "145+",
    establishedYear: 2018,
  },

  {
    companyName: "CareFirst Home Health",
    email: "info@carefirsthomehealth.com",
    phone: "+254 20 620 2500",
    website: "https://www.carefirsthomehealth.com",
    mainCategory: "Home Healthcare & Senior Care",
    subCategory: "Home Healthcare",
    specialty: "Post Surgical Care",
    country: "Kenya",
    state: "Nairobi County",
    city: "Nairobi",
    description: "Home healthcare specialists supporting recovery after surgery and long-term illness.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "125+",
    establishedYear: 2019,
  },

  {
    companyName: "Island Senior Wellness",
    email: "info@islandseniorwellness.com",
    phone: "+230 450 3300",
    website: "https://www.islandseniorwellness.com",
    mainCategory: "Home Healthcare & Senior Care",
    subCategory: "Senior Living & Assisted Care",
    specialty: "Long-Term Care",
    country: "Mauritius",
    state: "Port Louis",
    city: "Port Louis",
    description: "Senior wellness residence providing long-term care, rehabilitation and assisted living.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "118+",
    establishedYear: 2018,
  },

  {
    companyName: "Desert Home Healthcare",
    email: "info@deserthomehealthcare.com",
    phone: "+968 24 620 1900",
    website: "https://www.deserthomehealthcare.com",
    mainCategory: "Home Healthcare & Senior Care",
    subCategory: "Home Healthcare",
    specialty: "Home Nursing",
    country: "Oman",
    state: "Muscat",
    city: "Muscat",
    description: "Professional home nursing and rehabilitation services delivered in the comfort of patients' homes.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "138+",
    establishedYear: 2017,
  },

    {
    companyName: "Rapid Response Ambulance Services",
    email: "info@rapidresponseambulance.com",
    phone: "+91 11 6300 2100",
    website: "https://www.rapidresponseambulance.com",
    mainCategory: "Emergency & Medical Transportation",
    subCategory: "Ambulance Service",
    specialty: "Advanced Life Support Ambulance",
    country: "India",
    state: "Delhi",
    city: "New Delhi",
    description: "24/7 emergency ambulance services with advanced life support and critical care transport.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "180+",
    establishedYear: 2012,
  },

  {
    companyName: "SkyBridge Air Medical",
    email: "info@skybridgeairmedical.com",
    phone: "+971 4 650 2200",
    website: "https://www.skybridgeairmedical.com",
    mainCategory: "Emergency & Medical Transportation",
    subCategory: "Air Ambulance",
    specialty: "International Medical Evacuation",
    country: "UAE",
    state: "Dubai",
    city: "Dubai",
    description: "International air ambulance provider specializing in emergency medical evacuations worldwide.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.9,
    staffCount: "145+",
    establishedYear: 2011,
  },

  {
    companyName: "MedEquip Solutions",
    email: "info@medequipsolutions.com",
    phone: "+91 80 6400 2800",
    website: "https://www.medequipsolutions.com",
    mainCategory: "Pharmaceuticals, Medical Equipment & Supplies",
    subCategory: "Medical Equipment Supplier",
    specialty: "Hospital Equipment",
    country: "India",
    state: "Karnataka",
    city: "Bengaluru",
    description: "Supplier of hospital equipment, ICU devices and surgical technology for healthcare providers.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "230+",
    establishedYear: 2010,
  },

  {
    companyName: "Nova Medical Supplies",
    email: "info@novamedsupplies.com",
    phone: "+65 6950 3100",
    website: "https://www.novamedsupplies.com",
    mainCategory: "Pharmaceuticals, Medical Equipment & Supplies",
    subCategory: "Medical Supplies Distributor",
    specialty: "Clinical Consumables",
    country: "Singapore",
    state: "Singapore",
    city: "Singapore",
    description: "Distributor of medical consumables, disposables and infection control products.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "185+",
    establishedYear: 2013,
  },

  {
    companyName: "Restore Rehabilitation Centre",
    email: "info@restorerehab.com",
    phone: "+91 20 6400 4100",
    website: "https://www.restorerehab.com",
    mainCategory: "Wellness, Rehabilitation & Preventive Care",
    subCategory: "Rehabilitation Center",
    specialty: "Physical Rehabilitation",
    country: "India",
    state: "Maharashtra",
    city: "Pune",
    description: "Comprehensive rehabilitation centre providing neurological, orthopedic and sports recovery programs.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "210+",
    establishedYear: 2014,
  },

  {
    companyName: "WellSpring Wellness Clinic",
    email: "info@wellspringwellness.com",
    phone: "+60 3 6300 5200",
    website: "https://www.wellspringwellness.com",
    mainCategory: "Wellness, Rehabilitation & Preventive Care",
    subCategory: "Wellness Center",
    specialty: "Preventive Health",
    country: "Malaysia",
    state: "Kuala Lumpur",
    city: "Kuala Lumpur",
    description: "Preventive healthcare and wellness centre focused on lifestyle medicine and executive health programs.",
    tier: "STANDARD",
    featured: false,
    rating: 4.6,
    staffCount: "135+",
    establishedYear: 2016,
  },

  {
    companyName: "VirtualCare Connect",
    email: "info@virtualcareconnect.com",
    phone: "+44 20 7000 4100",
    website: "https://www.virtualcareconnect.com",
    mainCategory: "Telemedicine & Digital Health",
    subCategory: "Telemedicine Platform",
    specialty: "Virtual Consultations",
    country: "United Kingdom",
    state: "England",
    city: "London",
    description: "Digital healthcare platform providing secure virtual consultations and remote patient monitoring.",
    tier: "PREMIUM",
    featured: true,
    rating: 4.8,
    staffCount: "160+",
    establishedYear: 2018,
  },

  {
    companyName: "HealthSecure Assistance",
    email: "info@healthsecureassistance.com",
    phone: "+971 2 650 3100",
    website: "https://www.healthsecureassistance.com",
    mainCategory: "Insurance, Assistance & Claims",
    subCategory: "Medical Assistance Company",
    specialty: "International Patient Assistance",
    country: "UAE",
    state: "Abu Dhabi",
    city: "Abu Dhabi",
    description: "Medical assistance company coordinating international healthcare access and case management.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "120+",
    establishedYear: 2015,
  },

  {
    companyName: "Healthcare Growth Partners",
    email: "info@healthcaregrowthpartners.com",
    phone: "+91 40 6500 4200",
    website: "https://www.healthcaregrowthpartners.com",
    mainCategory: "Healthcare Business Solutions",
    subCategory: "Healthcare Consulting",
    specialty: "Hospital Strategy",
    country: "India",
    state: "Telangana",
    city: "Hyderabad",
    description: "Healthcare consulting firm supporting hospitals with strategy, operations and digital transformation.",
    tier: "STANDARD",
    featured: false,
    rating: 4.7,
    staffCount: "95+",
    establishedYear: 2017,
  },

  {
    companyName: "Global Health Outreach Foundation",
    email: "info@globalhealthoutreach.org",
    phone: "+41 22 700 3200",
    website: "https://www.globalhealthoutreach.org",
    mainCategory: "Government, NGOs & Public Health",
    subCategory: "Public Health NGO",
    specialty: "Community Healthcare Programs",
    country: "Switzerland",
    state: "Geneva",
    city: "Geneva",
    description: "International public health organization supporting healthcare access, disease prevention and humanitarian medical initiatives.",
    tier: "STANDARD",
    featured: true,
    rating: 4.9,
    staffCount: "260+",
    establishedYear: 2004,
  },
];
